-- Run this entire file in Supabase SQL Editor.
-- Anonymous sign-ins must be enabled in Authentication settings.

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.room_members (
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'Someone',
  joined_at timestamptz not null default now(),
  primary key(room_id,user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'Someone',
  body text not null check (char_length(body) between 1 and 4000),
  reply_to bigint references public.messages(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.message_reactions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (char_length(reaction) between 1 and 8),
  created_at timestamptz not null default now(),
  primary key(message_id,user_id,reaction)
);

create index if not exists messages_room_created_idx on public.messages(room_id,created_at);
create index if not exists members_user_idx on public.room_members(user_id);

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;

create or replace function public.is_room_member(p_room uuid)
returns boolean language sql security definer set search_path=public stable as $$
  select exists(select 1 from public.room_members where room_id=p_room and user_id=auth.uid());
$$;

create or replace function public.create_room(p_code text, p_display_name text)
returns public.rooms language plpgsql security definer set search_path=public as $$
declare r public.rooms;
begin
  insert into public.rooms(code,owner_id) values(upper(trim(p_code)),auth.uid()) returning * into r;
  insert into public.room_members(room_id,user_id,display_name)
    values(r.id,auth.uid(),left(coalesce(nullif(trim(p_display_name),''),'Someone'),60));
  return r;
end $$;

create or replace function public.join_room(p_code text, p_display_name text)
returns public.rooms language plpgsql security definer set search_path=public as $$
declare r public.rooms;
begin
  select * into r from public.rooms where code=upper(trim(p_code));
  if not found then raise exception 'Room not found'; end if;
  insert into public.room_members(room_id,user_id,display_name)
    values(r.id,auth.uid(),left(coalesce(nullif(trim(p_display_name),''),'Someone'),60))
    on conflict(room_id,user_id) do update set display_name=excluded.display_name;
  return r;
end $$;

drop policy if exists rooms_member_select on public.rooms;
create policy rooms_member_select on public.rooms for select to authenticated using (public.is_room_member(id));

drop policy if exists members_select on public.room_members;
create policy members_select on public.room_members for select to authenticated using (public.is_room_member(room_id));

drop policy if exists members_insert on public.room_members;
create policy members_insert on public.room_members for insert to authenticated with check (user_id=auth.uid());

drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select to authenticated using (public.is_room_member(room_id));

drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check (user_id=auth.uid() and public.is_room_member(room_id));

drop policy if exists messages_delete_own on public.messages;
create policy messages_delete_own on public.messages for delete to authenticated using (user_id=auth.uid() and public.is_room_member(room_id));

drop policy if exists reactions_select on public.message_reactions;
create policy reactions_select on public.message_reactions for select to authenticated using (
  exists(select 1 from public.messages m where m.id=message_id and public.is_room_member(m.room_id))
);

drop policy if exists reactions_insert on public.message_reactions;
create policy reactions_insert on public.message_reactions for insert to authenticated with check (
  user_id=auth.uid() and exists(select 1 from public.messages m where m.id=message_id and public.is_room_member(m.room_id))
);

drop policy if exists reactions_delete_own on public.message_reactions;
create policy reactions_delete_own on public.message_reactions for delete to authenticated using (user_id=auth.uid());

grant execute on function public.create_room(text,text) to authenticated;
grant execute on function public.join_room(text,text) to authenticated;

-- Realtime publication. If a table is already present, these statements may report
-- a harmless "already member" error in some projects; the tables remain usable.
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.message_reactions;
